version: '3.1'

services:
  airbnbcarousel:
    build: Service/
    depends_on:
      - 'database'
    ports:
      - '3003:3003'
      
  database:
    build: Database/
    ports:
    - '5432:5432'

